name: notch-observability
networks:
  notch-observability-network:
    name: notch-observability-network
services:
  ingester:
    command:
    - -c
    - |
      /signoz-otel-collector migrate sync check &&
      /signoz-otel-collector --config=/etc/otel-collector-config.yaml --manager-config=/etc/opamp-config.yaml --copy-path=/var/tmp/collector-config.yaml
    entrypoint:
    - /bin/sh
    environment:
    - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://notch-observability-telemetrystore-clickhouse-0-0:9000
    - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    image: signoz/signoz-otel-collector:v0.142.0
    networks:
      notch-observability-network:
        aliases:
        - notch-observability-ingester
    ports:
    - 4317:4317
    - 4318:4318
    restart: unless-stopped
    volumes:
    - ./ingester/ingester.yaml:/etc/otel-collector-config.yaml:ro
    - ./ingester/opamp.yaml:/etc/opamp-config.yaml:ro
  notch-observability-metastore-postgres-0:
    container_name: notch-observability-metastore-postgres-0
    environment:
    - POSTGRES_DB=signoz
    - POSTGRES_PASSWORD=signoz
    - POSTGRES_USER=signoz
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD-SHELL
      - pg_isready -U signoz -d signoz
      timeout: 10s
    image: postgres:16
    networks:
    - notch-observability-network
    restart: unless-stopped
    volumes:
    - notch-observability-metastore-postgres-0-data:/var/lib/postgresql/data
  notch-observability-signoz-0:
    container_name: notch-observability-signoz-0
    environment:
    - SIGNOZ_SQLSTORE_POSTGRES_DSN=postgres://signoz:signoz@notch-observability-metastore-postgres-0:5432/signoz?sslmode=disable
    - SIGNOZ_SQLSTORE_PROVIDER=postgres
    - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://notch-observability-telemetrystore-clickhouse-0-0:9000
    - SIGNOZ_TELEMETRYSTORE_PROVIDER=clickhouse
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:8080/api/v1/health
      timeout: 10s
    image: signoz/signoz:v0.134.0
    networks:
    - notch-observability-network
    ports:
    - 8080:8080
    restart: unless-stopped
  notch-observability-telemetrykeeper-zookeeper-0:
    container_name: notch-observability-telemetrykeeper-zookeeper-0
    environment:
    - ZOO_SERVER_ID=1
    - ALLOW_ANONYMOUS_LOGIN=yes
    - ZOO_4LW_COMMANDS_WHITELIST=srvr, mntr, ruok
    - ZOO_AUTOPURGE_INTERVAL=1
    - ZOO_AUTOPURGE_RETAIN_COUNT=3
    - ZOO_ENABLE_PROMETHEUS_METRICS=yes
    - ZOO_HEAP_SIZE=1024
    - ZOO_INIT_LIMIT=10
    - ZOO_LOG_LEVEL=INFO
    - ZOO_MAX_CLIENT_CNXNS=60
    - ZOO_MAX_SESSION_TIMEOUT=40000
    - ZOO_PRE_ALLOC_SIZE=65536
    - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
    - ZOO_SNAPCOUNT=100000
    - ZOO_SYNC_LIMIT=5
    - ZOO_TICK_TIME=2000
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD-SHELL
      - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
      timeout: 10s
    image: signoz/zookeeper:3.7.1
    networks:
    - notch-observability-network
    restart: unless-stopped
    volumes:
    - notch-observability-telemetrykeeper-0-data:/bitnami/zookeeper
  notch-observability-telemetrystore-clickhouse-0-0:
    container_name: notch-observability-telemetrystore-clickhouse-0-0
    depends_on:
      notch-observability-telemetrykeeper-zookeeper-0:
        condition: service_healthy
      notch-observability-telemetrystore-clickhouse-user-scripts:
        condition: service_completed_successfully
    environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1
    - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config-0-0.yaml
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:8123/ping
      timeout: 10s
    image: clickhouse/clickhouse-server:25.12.5
    networks:
    - notch-observability-network
    ports:
    - 8123:8123
    - 9000:9000
    restart: unless-stopped
    volumes:
    - notch-observability-telemetrystore-0-0-data:/var/lib/clickhouse
    - notch-observability-telemetrystore-user-scripts:/var/lib/clickhouse/user_scripts:ro
    - ./telemetrystore/clickhouse/config-0-0.yaml:/etc/clickhouse-server/config-0-0.yaml:ro
    - ./telemetrystore/clickhouse/functions.yaml:/etc/clickhouse-server/functions.yaml:ro
  notch-observability-telemetrystore-clickhouse-0-1:
    container_name: notch-observability-telemetrystore-clickhouse-0-1
    depends_on:
      notch-observability-telemetrykeeper-zookeeper-0:
        condition: service_healthy
      notch-observability-telemetrystore-clickhouse-user-scripts:
        condition: service_completed_successfully
    environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1
    - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config-0-1.yaml
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:8123/ping
      timeout: 10s
    image: clickhouse/clickhouse-server:25.12.5
    networks:
    - notch-observability-network
    restart: unless-stopped
    volumes:
    - notch-observability-telemetrystore-0-1-data:/var/lib/clickhouse
    - notch-observability-telemetrystore-user-scripts:/var/lib/clickhouse/user_scripts:ro
    - ./telemetrystore/clickhouse/config-0-1.yaml:/etc/clickhouse-server/config-0-1.yaml:ro
    - ./telemetrystore/clickhouse/functions.yaml:/etc/clickhouse-server/functions.yaml:ro
  notch-observability-telemetrystore-clickhouse-user-scripts:
    command:
    - bash
    - -c
    - |-
      version="v0.0.1"
      node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
      node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
      echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
      cd /tmp
      wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
      tar -xvzf histogram-quantile.tar.gz
      mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    container_name: notch-observability-telemetrystore-clickhouse-user-scripts
    image: clickhouse/clickhouse-server:25.12.5
    networks:
    - notch-observability-network
    restart: on-failure
    volumes:
    - notch-observability-telemetrystore-user-scripts:/var/lib/clickhouse/user_scripts
  notch-observability-telemetrystore-migrator:
    command:
    - -c
    - |
      /signoz-otel-collector migrate ready &&
      /signoz-otel-collector migrate bootstrap &&
      /signoz-otel-collector migrate sync up &&
      /signoz-otel-collector migrate async up
    container_name: notch-observability-telemetrystore-migrator
    entrypoint:
    - /bin/sh
    environment:
    - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://notch-observability-telemetrystore-clickhouse-0-0:9000
    - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    image: signoz/signoz-otel-collector:v0.142.0
    networks:
    - notch-observability-network
    restart: on-failure
volumes:
  notch-observability-metastore-postgres-0-data:
    name: notch-observability-metastore-postgres-0-data
  notch-observability-telemetrykeeper-0-data:
    name: notch-observability-telemetrykeeper-0-data
  notch-observability-telemetrystore-0-0-data:
    name: notch-observability-telemetrystore-0-0-data
  notch-observability-telemetrystore-0-1-data:
    name: notch-observability-telemetrystore-0-1-data
  notch-observability-telemetrystore-user-scripts:
    name: notch-observability-telemetrystore-user-scripts
